### ISSUE TITLE
CD generation for user-data fails on macos

### ISSUE THREAD

**Issue by viraptor** [hashicorp/packer-plugin-qemu#133]
#### Overview of the Issue

The options to create the `user-data` cd don't work well on macos. The `.iso`s seem to be created just fine and look reasonable, but they're not detected by cloud-init.

#### Reproduction Steps

Try using a user-data generated on macos with either `mkisofs` or `hdiutil`.
The iso is in place, but gets ignored by the image from `https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64.img`
I did not dig into the differences too much.

On the other hand, the same user-data packed using `cloud-localds` on linux gets detected and processed just fine. To test, I replaced `hdiutil` with:
```
#!/bin/sh
cp user-data.img $3
```
and used the image copied from linux.

Ok, so these are all external tools, why am I reporting it here? Mainly in case this is a general issue with `hdiutil` and it should be removed from the list.
I can't easily tell what the difference is between the different isos yet. I'll attach the a package with the 2 failing and 1 working version.
[isos.tar.gz](https://github.com/hashicorp/packer-plugin-qemu/files/11037683/isos.tar.gz)

### Plugin and Packer version

1.8.4

### Simplified Packer Buildfile

```
source "qemu" "local-build" {
  iso_checksum = "none"
  iso_url = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64.img"
  disk_image = true
  output_directory = "built-images"
  disk_size = "5000M"
  format = "qcow2"
  qemu_binary = "qemu-system-aarch64"
  headless = true
  use_default_display = true
  firmware = "edk2-aarch64-code.fd"
  machine_type = "virt,highmem=off"
  cpu_model = "host"
  accelerator = "hvf"
  ssh_username = "ubuntu"
  ssh_password = "ubuntu"
  cd_files = [ "user-data" ]
  cd_label = "cidata"
}
```

The `user-data` contains:
```
#cloud-config
users:
  - name: ubuntu
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: False
    plain_text_passwd: "ubuntu"
runcmd:
  - [ sed, "-e", "s/^PasswordAuthentication.*/PasswordAuthentication yes/", "-i", "/etc/ssh/sshd_config" ]
  - [ systemctl, restart, ssh ]
```

### Operating system and Environment details

Darwin Kernel Version 22.3.0, M2, aarch64

### Log Fragments and crash.log files

Nothing relevant beyond the user never being created.
